// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(FabrikaContext))]
    partial class FabrikaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Boja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Boje");
                });

            modelBuilder.Entity("Models.Fabrika", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrKontejnera")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Fabrike");
                });

            modelBuilder.Entity("Models.Kontejner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BojaID")
                        .HasColumnType("int");

                    b.Property<int?>("FabrikaID")
                        .HasColumnType("int");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int");

                    b.Property<int>("TrenutniKapacitet")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BojaID");

                    b.HasIndex("FabrikaID");

                    b.ToTable("Kontejneri");
                });

            modelBuilder.Entity("Models.Kontejner", b =>
                {
                    b.HasOne("Models.Boja", "Boja")
                        .WithMany("Kontejneri")
                        .HasForeignKey("BojaID");

                    b.HasOne("Models.Fabrika", "Fabrika")
                        .WithMany("Kontejneri")
                        .HasForeignKey("FabrikaID");

                    b.Navigation("Boja");

                    b.Navigation("Fabrika");
                });

            modelBuilder.Entity("Models.Boja", b =>
                {
                    b.Navigation("Kontejneri");
                });

            modelBuilder.Entity("Models.Fabrika", b =>
                {
                    b.Navigation("Kontejneri");
                });
#pragma warning restore 612, 618
        }
    }
}
