// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ProdavnicaContext))]
    partial class ProdavnicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Artikal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Brend")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SifraModela")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("Server.Models.ArtikalUProdaji", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ArtikalID")
                        .HasColumnType("int");

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<int>("KolicinaL")
                        .HasColumnType("int");

                    b.Property<int>("KolicinaM")
                        .HasColumnType("int");

                    b.Property<int>("KolicinaS")
                        .HasColumnType("int");

                    b.Property<int?>("ProdavnicaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ArtikalID");

                    b.HasIndex("ProdavnicaID");

                    b.ToTable("ArtikliUProdaji");
                });

            modelBuilder.Entity("Server.Models.Prodavnica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Prodavnice");
                });

            modelBuilder.Entity("Server.Models.ArtikalUProdaji", b =>
                {
                    b.HasOne("Server.Models.Artikal", "Artikal")
                        .WithMany("ArtikliUProdaji")
                        .HasForeignKey("ArtikalID");

                    b.HasOne("Server.Models.Prodavnica", "Prodavnica")
                        .WithMany("ArtikliUProdaji")
                        .HasForeignKey("ProdavnicaID");

                    b.Navigation("Artikal");

                    b.Navigation("Prodavnica");
                });

            modelBuilder.Entity("Server.Models.Artikal", b =>
                {
                    b.Navigation("ArtikliUProdaji");
                });

            modelBuilder.Entity("Server.Models.Prodavnica", b =>
                {
                    b.Navigation("ArtikliUProdaji");
                });
#pragma warning restore 612, 618
        }
    }
}
