// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace OktobarTri2025.Migrations
{
    [DbContext(typeof(ProdavnicaContext))]
    [Migration("20260328141126_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Kategorija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("Models.Prodavnica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BrTelefona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Prodavnice");
                });

            modelBuilder.Entity("Models.Proizvod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("kategorijaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("kategorijaID");

                    b.ToTable("Proizvodi");
                });

            modelBuilder.Entity("Models.ProizvodUProdavnici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("prodavnicaID")
                        .HasColumnType("int");

                    b.Property<int?>("proizvodID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("prodavnicaID");

                    b.HasIndex("proizvodID");

                    b.ToTable("ProizvodiUProdavnici");
                });

            modelBuilder.Entity("Models.Proizvod", b =>
                {
                    b.HasOne("Models.Kategorija", "kategorija")
                        .WithMany("Proizvodi")
                        .HasForeignKey("kategorijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kategorija");
                });

            modelBuilder.Entity("Models.ProizvodUProdavnici", b =>
                {
                    b.HasOne("Models.Prodavnica", "prodavnica")
                        .WithMany("ProizvodiUProdavnici")
                        .HasForeignKey("prodavnicaID");

                    b.HasOne("Models.Proizvod", "proizvod")
                        .WithMany("ProizvodiUProdavnici")
                        .HasForeignKey("proizvodID");

                    b.Navigation("prodavnica");

                    b.Navigation("proizvod");
                });

            modelBuilder.Entity("Models.Kategorija", b =>
                {
                    b.Navigation("Proizvodi");
                });

            modelBuilder.Entity("Models.Prodavnica", b =>
                {
                    b.Navigation("ProizvodiUProdavnici");
                });

            modelBuilder.Entity("Models.Proizvod", b =>
                {
                    b.Navigation("ProizvodiUProdavnici");
                });
#pragma warning restore 612, 618
        }
    }
}
