// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace KlkBiblioteka.Migrations
{
    [DbContext(typeof(BibliotekaContext))]
    partial class BibliotekaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Biblioteka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Biblioteke");
                });

            modelBuilder.Entity("Models.Izdavanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVracanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("bibliotekaID")
                        .HasColumnType("int");

                    b.Property<int?>("knjigaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("bibliotekaID");

                    b.HasIndex("knjigaID");

                    b.ToTable("Izdavanja");
                });

            modelBuilder.Entity("Models.Knjiga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojUEvidencijiBiblioteke")
                        .HasColumnType("int");

                    b.Property<int>("GodinaIzdavanja")
                        .HasColumnType("int");

                    b.Property<string>("ImeAutora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivIzdavaca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("bibliotekaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("bibliotekaID");

                    b.ToTable("Knjige");
                });

            modelBuilder.Entity("Models.Izdavanje", b =>
                {
                    b.HasOne("Models.Biblioteka", "biblioteka")
                        .WithMany("Izdavanja")
                        .HasForeignKey("bibliotekaID");

                    b.HasOne("Models.Knjiga", "knjiga")
                        .WithMany("Izdavanja")
                        .HasForeignKey("knjigaID");

                    b.Navigation("biblioteka");

                    b.Navigation("knjiga");
                });

            modelBuilder.Entity("Models.Knjiga", b =>
                {
                    b.HasOne("Models.Biblioteka", "biblioteka")
                        .WithMany("Knjige")
                        .HasForeignKey("bibliotekaID");

                    b.Navigation("biblioteka");
                });

            modelBuilder.Entity("Models.Biblioteka", b =>
                {
                    b.Navigation("Izdavanja");

                    b.Navigation("Knjige");
                });

            modelBuilder.Entity("Models.Knjiga", b =>
                {
                    b.Navigation("Izdavanja");
                });
#pragma warning restore 612, 618
        }
    }
}
