// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace RekorderZadatak.Migrations
{
    [DbContext(typeof(TakmicenjeContext))]
    partial class TakmicenjeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Disciplina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrenutniBrTakmicara")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Discipline");
                });

            modelBuilder.Entity("Models.Rekord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("InformacijaOTakmicenju")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("disciplinaID")
                        .HasColumnType("int");

                    b.Property<int?>("rekorderID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("disciplinaID");

                    b.HasIndex("rekorderID");

                    b.ToTable("Rekordi");
                });

            modelBuilder.Entity("Models.Rekorder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Rekorderi");
                });

            modelBuilder.Entity("Models.Rekord", b =>
                {
                    b.HasOne("Models.Disciplina", "disciplina")
                        .WithMany("rekordi")
                        .HasForeignKey("disciplinaID");

                    b.HasOne("Models.Rekorder", "rekorder")
                        .WithMany("rekordi")
                        .HasForeignKey("rekorderID");

                    b.Navigation("disciplina");

                    b.Navigation("rekorder");
                });

            modelBuilder.Entity("Models.Disciplina", b =>
                {
                    b.Navigation("rekordi");
                });

            modelBuilder.Entity("Models.Rekorder", b =>
                {
                    b.Navigation("rekordi");
                });
#pragma warning restore 612, 618
        }
    }
}
