// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace MaterijalStovariste.Migrations
{
    [DbContext(typeof(StovaristeContext))]
    partial class StovaristeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.IsporucenMaterijal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumIsporuke")
                        .HasColumnType("datetime2");

                    b.Property<int>("KolicinaMaterijala")
                        .HasColumnType("int");

                    b.Property<int?>("materijalID")
                        .HasColumnType("int");

                    b.Property<int?>("stovaristeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("materijalID");

                    b.HasIndex("stovaristeID");

                    b.ToTable("IsporuceniMaterijali");
                });

            modelBuilder.Entity("Models.Materijal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("Cena")
                        .HasColumnType("real");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivProizvodjaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Materijali");
                });

            modelBuilder.Entity("Models.Stovariste", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Stovarista");
                });

            modelBuilder.Entity("Models.IsporucenMaterijal", b =>
                {
                    b.HasOne("Models.Materijal", "materijal")
                        .WithMany("IsporuceniMaterijali")
                        .HasForeignKey("materijalID");

                    b.HasOne("Models.Stovariste", "stovariste")
                        .WithMany("IsporuceniMaterijali")
                        .HasForeignKey("stovaristeID");

                    b.Navigation("materijal");

                    b.Navigation("stovariste");
                });

            modelBuilder.Entity("Models.Materijal", b =>
                {
                    b.Navigation("IsporuceniMaterijali");
                });

            modelBuilder.Entity("Models.Stovariste", b =>
                {
                    b.Navigation("IsporuceniMaterijali");
                });
#pragma warning restore 612, 618
        }
    }
}
