// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(SendviciContext))]
    partial class SendviciContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Mesto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProdavnicaID")
                        .HasColumnType("int");

                    b.Property<int>("UkupnaCena")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProdavnicaID");

                    b.ToTable("Mesta");
                });

            modelBuilder.Entity("Models.Prodavnica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Prodavnice");
                });

            modelBuilder.Entity("Models.Sastojak", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Sastojci");
                });

            modelBuilder.Entity("Models.SastojakUProdavnici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("ProdavnicaID")
                        .HasColumnType("int");

                    b.Property<int?>("SastojakID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProdavnicaID");

                    b.HasIndex("SastojakID");

                    b.ToTable("SastojciUProdavnici");
                });

            modelBuilder.Entity("Models.SastojakUSendvicu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("MestoID")
                        .HasColumnType("int");

                    b.Property<int?>("SastojakUProdavniciID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MestoID");

                    b.HasIndex("SastojakUProdavniciID");

                    b.ToTable("SastojciUSendvicu");
                });

            modelBuilder.Entity("Models.Mesto", b =>
                {
                    b.HasOne("Models.Prodavnica", "Prodavnica")
                        .WithMany("Mesta")
                        .HasForeignKey("ProdavnicaID");

                    b.Navigation("Prodavnica");
                });

            modelBuilder.Entity("Models.SastojakUProdavnici", b =>
                {
                    b.HasOne("Models.Prodavnica", "Prodavnica")
                        .WithMany("SastojciUProdavnici")
                        .HasForeignKey("ProdavnicaID");

                    b.HasOne("Models.Sastojak", "Sastojak")
                        .WithMany("SastojciUProdavnici")
                        .HasForeignKey("SastojakID");

                    b.Navigation("Prodavnica");

                    b.Navigation("Sastojak");
                });

            modelBuilder.Entity("Models.SastojakUSendvicu", b =>
                {
                    b.HasOne("Models.Mesto", "Mesto")
                        .WithMany("SastojciUSendvicu")
                        .HasForeignKey("MestoID");

                    b.HasOne("Models.SastojakUProdavnici", "SastojakUProdavnici")
                        .WithMany("SastojciUSendvicu")
                        .HasForeignKey("SastojakUProdavniciID");

                    b.Navigation("Mesto");

                    b.Navigation("SastojakUProdavnici");
                });

            modelBuilder.Entity("Models.Mesto", b =>
                {
                    b.Navigation("SastojciUSendvicu");
                });

            modelBuilder.Entity("Models.Prodavnica", b =>
                {
                    b.Navigation("Mesta");

                    b.Navigation("SastojciUProdavnici");
                });

            modelBuilder.Entity("Models.Sastojak", b =>
                {
                    b.Navigation("SastojciUProdavnici");
                });

            modelBuilder.Entity("Models.SastojakUProdavnici", b =>
                {
                    b.Navigation("SastojciUSendvicu");
                });
#pragma warning restore 612, 618
        }
    }
}
