// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace LekarBolnica.Migrations
{
    [DbContext(typeof(BolnicaContext))]
    partial class BolnicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Bolnica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojOdeljenja")
                        .HasColumnType("int");

                    b.Property<int>("BrojOsoblja")
                        .HasColumnType("int");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bolnice");
                });

            modelBuilder.Entity("Models.Lekar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumDiplomiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumDobijanjaLicence")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Lekari");
                });

            modelBuilder.Entity("Models.LekarUBolnici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumPOtpisivanjaUgovora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specijalnost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("bolnicaID")
                        .HasColumnType("int");

                    b.Property<int?>("lekarID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("bolnicaID");

                    b.HasIndex("lekarID");

                    b.ToTable("LekariUBolnici");
                });

            modelBuilder.Entity("Models.LekarUBolnici", b =>
                {
                    b.HasOne("Models.Bolnica", "bolnica")
                        .WithMany("LekariUBolnici")
                        .HasForeignKey("bolnicaID");

                    b.HasOne("Models.Lekar", "lekar")
                        .WithMany("LekariUBolnici")
                        .HasForeignKey("lekarID");

                    b.Navigation("bolnica");

                    b.Navigation("lekar");
                });

            modelBuilder.Entity("Models.Bolnica", b =>
                {
                    b.Navigation("LekariUBolnici");
                });

            modelBuilder.Entity("Models.Lekar", b =>
                {
                    b.Navigation("LekariUBolnici");
                });
#pragma warning restore 612, 618
        }
    }
}
